name: CI SmartCard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer dépendances Python
        run: |
          pip install pytest flake8 bandit

      - name: Qualité du code Python
        run: flake8 .

      - name: Tests Python
        run: pytest

      - name: Scan sécurité Python
        run: bandit -r .

      - name: Installer Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer ESLint
        run: npm install eslint

      - name: Analyse JavaScript
        run: npx eslint .
